### ISSUE TITLE
connectToWifi returns true without connecting to the network

### ISSUE THREAD

**Issue by nikolaj808-itminds** [wonjerry/flutter_wifi_connector#17] opened 2022-01-27 08:08 UTC
Using a device running Android 11, when I attempt to connect to a private network, it returns true, even though it does not connect to the WiFi network.
All the correct permissions have been added to the AndroidManifest.xml and there is no problem with `flutter doctor`.

**Comment by vanlooverenkoen** [comment] 2022-02-08 14:24
This is because the current implementation is not supporting the latest API's
I was working on #13 but the android API very poorly documented. So I am reworking everything.

**Comment by vanlooverenkoen** [comment] 2022-02-08 14:25
duplicate of #12

**Closed** 2022-02-11 08:06 UTC
